### PR TITLE
Replace Travis CI badge with GitHub Actions badge

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
Before:
image
After:
image

### CODE REVIEW

**Comment by andreasabel** [comment]
@gdziadkiewicz : Now we would also need a badge for the Win/Mac build...

**Comment by gdziadkiewicz** [comment]
Ok, I will add it

**Comment by gdziadkiewicz** [comment]
After adding second badge:
image

**Comment by andreasabel** [comment]
Perfect, thanks!

**Pull request merged**
