### PR TITLE
Fix ShellCmd String arguments

### LINKED ISSUE #143: `cmd` does not work with `String` argument
Hi.

`cmd` does not work with `String` argument, because ghc uses
`ShellCmd ([arg] -> result)` instance and looks for `CmdArg Char` instance.

>       {-# LANGUAGE OverloadedStrings #-}
>       {-# LANGUAGE ExtendedDefaultRules #-}
>       {-# OPTIONS_GHC -fno-warn-type-defaults #-}
>       import Shelly
>       import qualified Data.Text as T
>       default (T.Text)
>
>       -- Does not work.
>       strCmd :: Sh ()
>       strCmd  = cmd "ls" ("." :: String)
>
>       -- Works as expected.
>       strCmdL :: Sh ()
>       strCmdL = cmd "ls" ["." :: String]

fails with error

    [4 of 4] Compiling Main             ( 1.hs, interpreted )

    1.hs:9:11: error:
        • No instance for (CmdArg Char) arising from a use of ‘cmd’
        • In the expression: cmd "ls" ("." :: String)
          In an equation for ‘strCmd’: strCmd = cmd "ls" ("." :: String)

This may be fixed, if we make

    instance CmdArg a => CmdArg [a] where

instead of

    instance (CmdArg arg, ShellCmd result) => ShellCmd ([arg] -> result) where

This requires changing the type of `toTextArg` too, though.

### PR DESCRIPTION
**Pull request by cunningdefenestrator**
Fixes #143.

Changelog:
- Rework ShellCmd's instances to support String arguments.
- Add some tests.
- Remove the IncoherentInstances pragma as it's deprecated.
- Bump the major version as CmdArg's method has changed.
- Bump the resolver to lts-20.04 (the latest as of this writing).
- Bump haskell-ci to 0.15.20221107

### CODE REVIEW

**Comment by cunningdefenestrator** [comment]
Looks likes this succeeds for everything but ghc 8.0.2--I'm not sure why because AFAICT the instance selection rules haven't changed.  How should I proceed?

**Comment by andreasabel** [comment]
@cunningdefenestrator : Thanks for the PR. 
I couldn't push to your branch (permission denied).  Could you give me permission?
In the meanwhile, I backed this PR up to:
- #223

**Comment by andreasabel** [comment]
> Looks likes this succeeds for everything but ghc 8.0.2--I'm not sure why because AFAICT the instance selection rules haven't changed. How should I proceed?

GHC 8.0 can be considered a legacy GHC by now, so a pragmatic solution would be to drop GHC 8.0.
(One could also investigate whether/how the broken files could be fixed for GHC 8.0.)

You suggest a major-major version bump to 2.0.0---do you expect a lot of breakage?

**Comment by cunningdefenestrator** [comment]
@andreasabel I've sent an invite.

If we're being strict about SemVer this deserves a major version bump since I changed the signature of `CmdArgs`.  In practice, I don't think too many people would use `CmdArgs` directly, but I'll defer to your judgment here.

I suspect that re-enabling IncoherentInstances as a top-level pragma might work for GHC 8.0, but given that it's deprecated I think dropping support would be better.

**Comment by andreasabel** [comment]
> @andreasabel I've sent an invite.

Thanks! For now, it is more convenient for me to continue on #223, but I might come back to this.

> If we're being strict about SemVer this deserves a major version bump since I changed the signature of `CmdArgs`. In practice, I don't think too many people would use `CmdArgs` directly, but I'll defer to your judgment here.

Yes, definitely a major version bump.  I it only that `shelly` (like most Haskell packages) follow the Haskell PVP whether the first _two_ numbers are major, the third is minor, and the fourth is patch version.  Thus, `1.12.0` would already be a major version bump.  
If lots of breakage is expected, developers might opt for even a major-major version bump, like `2.0.0`.

> I suspect that re-enabling `IncoherentInstances` as a top-level pragma might work for GHC 8.0, but given that it's deprecated I think dropping support would be better.

I think if we drop 8.0 then a simple major bump to e.g. `1.12.0` would be sufficient for sure, but it might even be sufficient if we keep 8.0 and alert of the breakage, suggesting `IncoherentInstances` as a workaround.

**Review by andreasabel — APPROVED** [review]

**Comment by andreasabel** [comment]
@cunningdefenestrator : Shouldn't `Shelly.Pipe` then be changed in the same way? https://github.com/gregwebs/Shelly.hs/blob/d0b16a601b7f829431938b1ebaa699419a193653/src/Shelly/Pipe.hs#L612-L615
Also, since this is a breaking change, could you draft a migration guide, e.g. on top of the `ChangeLog.md` file?

**Review by andreasabel — CHANGES_REQUESTED** [review]
Remaining:
- question about `Shelly.Pipe`
- migration guide
- decide fate of GHC 8.0
- decide on version 1.12 vs. 2.0 (estimate breakage)

**Comment by cunningdefenestrator** [comment]
After familiarizing myself with the Haskell PVP, this doesn't justify a major.major bump, so I dropped the version back down to 1.12.0.  I've also added a note about migrating existing instances to the changelog, and I dropped support for GHC 8.0.

I'll make the corresponding change to `Shelly.Pipe` next.

**Comment by cunningdefenestrator** [comment]
@andreasabel 
Apologies for the long turnaround, but I've made the `Shelly.Pipe` changes.

**Review by andreasabel — APPROVED** [review]
Thanks!
I tested this PR on my local use of shelly and wrote a more concrete migration example based on the changes I made.
Also, since the changelog is for the user of the library (not for our own bookkeeping), I removed entries that are not relevant for the users.

**Comment by andreasabel** [comment]
Candidate: https://hackage.haskell.org/package/shelly-1.12.0/candidate

**Comment by andreasabel** [comment]
I reset this branch to remove my last 3 commits pertaining to the release of 1.12.0.

**Pull request merged**
