### PR TITLE
fixed windows build

### PR DESCRIPTION
**Pull request by rocketnik**

### CODE REVIEW

**Comment by hsenag** [comment]
This fails - I'm not sure there is a `readSymbolicLink` available for Windows (at least in the Haskell package):

```
src\Shelly\Directory.hs:26:5: error:
    Not in scope: `Win32.readSymbolicLink'
    Perhaps you meant one of these:
      `Win32.createSymbolicLink' (imported from System.Win32),
      Win32.createSymbolicLink' (imported from System.Win32),
      `Win32.c_CreateSymbolicLink' (imported from System.Win32)
    Module `System.Win32' does not export `readSymbolicLink'.
   |
26 |     Win32.readSymbolicLink path
   |     ^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by nekketsuuu** [comment]
[This blog post](https://blogs.msdn.microsoft.com/oldnewthing/20100212-00/?p=14963) says a target path of a symbolic link is obtained from a handle given by opening the link. And according to [this Microsoft document](https://docs.microsoft.com/en-us/windows/desktop/fileio/symbolic-link-effects-on-file-systems-functions), it seems that [`System.Win32.File.createFile`](http://hackage.haskell.org/package/Win32-2.8.0.0/docs/System-Win32-File.html#v:createFile) returns the handle. How about using this function?

**Comment by andreasabel** [comment]
There is https://hackage.haskell.org/package/unix-compat-0.5.3/docs/System-PosixCompat-Files.html#v:readSymbolicLink

**Comment by gregwebs** [comment]
closing in favor of #201

**Pull request closed without merging**
